# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bfb95502aa8f4f718b14d09136fef838"
application_url = "https://zapchat.solnix.store"
embedded = true
name = "ZapChat"
handle = "staging-76"

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""

[webhooks]
api_version = "2022-10"

[access_scopes]
scopes = "read_themes,write_themes,read_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://zapchat.solnix.store/auth/callback",
  "https://zapchat.solnix.store/auth/shopify/callback",
  "https://zapchat.solnix.store/api/auth/callback"
]

[app_proxy]
url = "https://zapchat.solnix.store/api/scroll-to-top"
subpath = "scroll-to-top"
prefix = "apps"

[pos]
embedded = false
